name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm install -g yarn
          yarn
          yarn run ci
          cp .ci.npmrc .npmrc
          yarn lerna publish from-package --pre-dist-tag next --yes
        env:
          CI: "true"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
